name: Run JSON Server

on:
  push:
    branches:
      - main

jobs:
  run-json-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install JSON Server
        run: npm install -g json-server

      - name: Start JSON Server
        run: json-server --watch public/db.json --port 5000
